service: "yams-${env:ENV}"

provider:
  name:       aws
  runtime:    nodejs6.10
  region:     ${env:AWS_DEFAULT_REGION, 'us-west-2'}
  stage:      ${opt:stage}
  memorySize: 128
  timeout:    2

  environment:
    ALLOW_CIDR: "${env:ALLOW_CIDR, 'x.x.x.x'}"

package:
  include:
    - node_modules/*
    - src/*.js
  exclude:
    - venv

functions:
  send:
    handler: src/send.send
    events:
      - stream:
          type: kinesis
          arn: { Fn::GetAtt: [ KinesisStream, Arn ] }
          batchSize: 100
          startingPosition: TRIM_HORIZON

resources:
  Resources:
    KinesisStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: "yams-${env:ENV}-send"
        ShardCount: 1
